SELECT
  [dbo_viesn_MPazinojumi].[JTMPazID],
  [dbo_viesn_MPazinojumi].[BP_Datums],
  [dbo_viesn_MPazinojumi].[BP_Nr],
  [dbo_viesn_MPazinojumi].[Ligums],
  [dbo_viesn_MPazinojumi].[Lig_Dat],
  [dbo_viesn_MPazinojumi].[Vards],
  [dbo_viesn_MPazinojumi].[Uzvards],
  [dbo_viesn_MPazinojumi].[Istaba],
  [dbo_viesn_MPazinojumi].[Par_No],
  [dbo_viesn_MPazinojumi].[Par_Lidz],
  [dbo_viesn_MPazinojumi].[Termins],
  [dbo_viesn_MPazinojumi].[Sagatavoja],
  [dbo_viesn_MPazinojumi].[Paraksta_Amats],
  [dbo_viesn_MPazinojumi].[Paraksta_Amats_eng],
  [dbo_viesn_MPazinojumi].[Paraksta_VU]
FROM
  dbo_viesn_MPazinojumi;
