CREATE TABLE [dbo_crl_Caurlaides] (
  [crl_Karte_ID] AUTOINCREMENT,
  [KartesTips] LONG,
  [Nr] LONG,
  [Datums] DATETIME,
  [Periods_No] DATETIME,
  [Periods_Lidz] DATETIME,
  [Cena] SINGLE,
  [AutoNr] VARCHAR (25),
  [PersID] LONG,
  [Vards] VARCHAR (50),
  [Uzvards] VARCHAR (50),
  [KlTips_ID] LONG,
  [KlTips] VARCHAR (50),
  [Stat] LONG,
  [Comment] VARCHAR (250),
  [Kase] LONG,
  [Aud_Date] DATETIME,
  [Aud_User] VARCHAR (50),
  [S_Date] DATETIME,
  [S_User] VARCHAR (50),
  [S_Sum] SINGLE,
  [Drukat] SHORT,
  [Drukat_Dat] DATETIME,
  [Drukat_sk] SHORT,
  [STRV_ID] LONG
)
